In [1]:
import numpy as np
from scipy import linalg

## Image Points and World Points

In [2]:
image = np.loadtxt('./assignment3/image.txt')
world = np.loadtxt('./assignment3/world.txt')

In [3]:
image_vector = np.concatenate((image,np.ones([1,image.shape[1]])),axis=0)
world_vector = np.concatenate((world,np.ones([1,world.shape[1]])),axis=0)

In [4]:
image_vector

array([[ 5.11770701,  5.5236545 ,  7.16310171,  5.22216628,  5.60479614,
        13.59494885,  8.73452189,  6.22433952,  9.74763886,  5.09031079],
       [ 4.76538441,  3.87032917,  7.35942066,  4.4279585 ,  4.67483648,
        10.05215495,  5.56420531,  3.90821885,  6.90423723,  4.5508513 ],
       [ 1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ,  1.        ,  1.        ,  1.        ,  1.        ]])

In [5]:
world_vector

array([[0.8518447 , 0.55793851, 0.81620571, 0.70368367, 0.71335444,
        0.1721997 , 0.04904683, 0.28614965, 0.13098247, 0.84767647],
       [0.75947939, 0.01423302, 0.97709235, 0.52206092, 0.2280389 ,
        0.96882014, 0.75533857, 0.25120055, 0.94081954, 0.20927164],
       [0.94975928, 0.59617708, 0.22190808, 0.93289706, 0.4496421 ,
        0.3557161 , 0.89481276, 0.93273619, 0.70185317, 0.45509169],
       [1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ]])

## Matrix A

In [6]:
A = np.zeros([2*image_vector.shape[1],12])
for i in range(image_vector.shape[1]):
    A[i][4:8] = -image_vector[2][i] * world_vector[:,i]
    A[i][8:12] = image_vector[1][i] * world_vector[:,i]
    A[10+i][:4] = image_vector[2][i]*world_vector[:,i]
    A[10+i][8:12] = -image_vector[0][i]*world_vector[:,i]


## Matrix P

In [7]:
U,D,V = np.linalg.svd(A)

In [8]:
P = V[-1:].reshape(3,4)
print(P)

[[ 1.27000127e-01  2.54000254e-01  3.81000381e-01  5.08000508e-01]
 [ 5.08000508e-01  3.81000381e-01  2.54000254e-01  1.27000127e-01]
 [ 1.27000127e-01 -2.77555756e-17  1.27000127e-01 -8.32667268e-17]]


## Reprojection Points and Image Points

In [9]:
re_projection = np.dot(P,world_vector)
re_projection = re_projection/re_projection[-1]

In [10]:
np.round_(re_projection,3)

array([[ 5.118,  5.524,  7.163,  5.222,  5.605, 13.595,  8.735,  6.224,
         9.748,  5.09 ],
       [ 4.765,  3.87 ,  7.359,  4.428,  4.675, 10.052,  5.564,  3.908,
         6.904,  4.551],
       [ 1.   ,  1.   ,  1.   ,  1.   ,  1.   ,  1.   ,  1.   ,  1.   ,
         1.   ,  1.   ]])

In [11]:
np.round_(image_vector,3)

array([[ 5.118,  5.524,  7.163,  5.222,  5.605, 13.595,  8.735,  6.224,
         9.748,  5.09 ],
       [ 4.765,  3.87 ,  7.359,  4.428,  4.675, 10.052,  5.564,  3.908,
         6.904,  4.551],
       [ 1.   ,  1.   ,  1.   ,  1.   ,  1.   ,  1.   ,  1.   ,  1.   ,
         1.   ,  1.   ]])

## Compute C using SVD

In [12]:
U, s, V = np.linalg.svd(P)
C = V[-1]
C = C[:-1]/C[-1]
C

array([ 1., -1., -1.])

## Compute C using RQ decomposition

In [13]:
r,q = linalg.rq(P, mode='economic')
R = (q.T)[:-1].T
t = (q.T)[-1].T
C_ = np.linalg.solve(-R,t)
C_

array([ 1., -1., -1.])